# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b9b2c88844fc30bd52fe6077f845be67"
name = "Terms & Conditions Checkbox"
application_url = "https://shopterm-production.up.railway.app"
embedded = true

[build]

[webhooks]
api_version = "2026-01"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://shopterm-production.up.railway.app/webhooks"
  customer_data_request_url = "https://shopterm-production.up.railway.app/webhooks"
  shop_deletion_url = "https://shopterm-production.up.railway.app/webhooks"

[access_scopes]
scopes = "read_orders,read_customers"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://shopterm-production.up.railway.app/auth/callback",
  "https://shopterm-production.up.railway.app/auth/shopify/callback",
  "https://shopterm-production.up.railway.app/api/auth/callback",
]

[app_proxy]
url = "https://shopterm-production.up.railway.app/api/consent"
subpath = "tc-consent"
prefix = "apps"

[pos]
embedded = false
