# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b9b2c88844fc30bd52fe6077f845be67"
name = "Terms & Conditions Checkbox"
application_url = "https://creation-dts-bike-headed.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://creation-dts-bike-headed.trycloudflare.com/webhooks"
  customer_data_request_url = "https://creation-dts-bike-headed.trycloudflare.com/webhooks"
  shop_deletion_url = "https://creation-dts-bike-headed.trycloudflare.com/webhooks"

[access_scopes]
scopes = "read_orders,read_customers"

[auth]
redirect_urls = [
  "https://creation-dts-bike-headed.trycloudflare.com/auth/callback",
  "https://creation-dts-bike-headed.trycloudflare.com/auth/shopify/callback",
  "https://creation-dts-bike-headed.trycloudflare.com/api/auth/callback",
]

[app_proxy]
url = "https://creation-dts-bike-headed.trycloudflare.com/api/consent"
subpath = "tc-consent"
prefix = "apps"

[pos]
embedded = false
